name: Deploy Nomee Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
        env:
          VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
          VITE_NOMEE_BACKEND_URL: ${{ secrets.VITE_NOMEE_BACKEND_URL }}
          VITE_NOMEE_BACKEND_WS_URL: ${{ secrets.VITE_NOMEE_BACKEND_WS_URL }}
          VITE_DOMA_URL: ${{ secrets.VITE_DOMA_URL }}
          VITE_DOMA_API_KEY: ${{ secrets.VITE_DOMA_API_KEY }}
          VITE_DOMA_GRAPHQL_URL: ${{ secrets.VITE_DOMA_GRAPHQL_URL }}
          VITE_REOWN_PROJECT_ID: ${{ secrets.VITE_REOWN_PROJECT_ID }}
          VITE_FIREBASE_VAPID: ${{ secrets.VITE_FIREBASE_VAPID }}

      - name: Sync S3 bucket
        uses: aws-actions/s3-sync@v2
        with:
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          region: ${{ secrets.AWS_REGION }}
          source-dir: dist
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        with:
          distribution-id: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          paths: "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
